Content for the main page
AdrianStankiewicz/FreshmanGuide pull request #11
Opened 2023-04-02 19:35 UTC by KacperLechicki

Added static content for the main page.

2023-04-02 19:56 UTC, OliwiaMilewska requested changes
Contact someone from content section to edit a little bit the paragraph do there is not so mamy repetitions. Maybe Lila could give you a hand with it?

2023-04-02 19:56 UTC, OliwiaMilewska commented on front-project/src/app/layouts/pages/home/home.component.html
> +          <p>Jedną z największych zalet studiowania jest możliwość nawiązywania nowych znajomości. Studenci studiujący w
*na* tym samym kierunku

2023-04-03 09:18 UTC, AdrianStankiewicz commented
@AdamKra3

2023-04-04 20:28 UTC, AdrianStankiewicz approved these changes

2023-04-04 20:44 UTC, OliwiaMilewska approved these changes

2023-04-04 20:45 UTC, merged