forum main page without paginator
AdrianStankiewicz/FreshmanGuide pull request #19
Opened 2023-04-24 18:05 UTC by KacperLechicki

forum main page with filters and reading/recognizing every post by id and creating specific url for each one, but without pagination and styles for single post component yet

2023-04-25 06:41 UTC, AdrianStankiewicz commented on front-project/src/app/layouts/pages/home/home.component.css
> +  /* ::-webkit-scrollbar-thumb {
Do we need to keep the commented part?

2023-04-25 07:05 UTC, KacperLechicki commented on front-project/src/app/layouts/pages/home/home.component.css
> +  /* ::-webkit-scrollbar-thumb {
The questions is do we want to have custom scrollbars. Because i can find better solutions, but we also can leave just the casual one.

2023-04-26 17:44 UTC, OliwiaMilewska requested changes

2023-04-26 17:44 UTC, OliwiaMilewska commented on front-project/src/app/app.module.ts
> +    ToastrModule.forRoot({}),
Is there a reason to add '{}'? Jus asking for curiosity :P

2023-04-26 17:44 UTC, OliwiaMilewska commented on front-project/src/app/models/category.ts
> +  post: Post[];
I believe in database we will leave only 'id' and 'name' so 'post' can be deleted.

2023-04-26 17:44 UTC, OliwiaMilewska commented on front-project/src/app/models/post.ts
> +  categoryId: Category;
Also categoryId will be just a number instead whole object.

2023-04-26 17:44 UTC, OliwiaMilewska commented on front-project/src/app/models/post.ts
>    verified: boolean;
I miss here list of Replies. 
replies: Reply[]
![image](https://user-images.githubusercontent.com/99407556/234658899-1d9f4ed7-d25e-415b-9400-692c8c290684.png)

2023-04-26 18:10 UTC, OliwiaMilewska approved these changes

2023-04-26 18:10 UTC, merged