Paginator and data matching new backend
AdrianStankiewicz/FreshmanGuide pull request #22
Opened 2023-04-26 22:12 UTC by KacperLechicki

Paginator works... I think so. I repaired forum to match new backend. I don't know why this request have all of this commits again, but eh...

2023-04-27 10:09 UTC, OliwiaMilewska commented on front-project/src/app/layouts/pages/forum/forum.component.html
> +            </option>
This can be one line.

2023-04-27 10:10 UTC, OliwiaMilewska requested changes

2023-04-27 10:10 UTC, OliwiaMilewska commented on front-project/src/app/layouts/pages/forum/forum.component.ts
> +  applyFilters(): any {
Hmm we don't like 'any' :(

2023-04-29 20:00 UTC, AdrianStankiewicz approved these changes

2023-05-04 18:01 UTC, OliwiaMilewska approved these changes

2023-05-04 18:01 UTC, merged