Adding replies works
AdrianStankiewicz/FreshmanGuide pull request #31
Opened 2023-05-27 19:21 UTC by KacperLechicki

Same way as posts

2023-05-27 19:32 UTC, OliwiaMilewska requested changes

2023-05-27 19:32 UTC, OliwiaMilewska commented on front-project/src/app/layouts/partials/reply-popup/reply-popup.component.ts
> +        console.log(response);
Maybe we should delete this console.log?

2023-05-27 20:11 UTC, KacperLechicki commented on front-project/src/app/layouts/partials/reply-popup/reply-popup.component.ts
> +        console.log(response);
We can't for now. Same thing as posts.

2023-05-27 20:35 UTC, AdrianStankiewicz approved these changes

2023-05-27 20:59 UTC, AdrianStankiewicz approved these changes

2023-05-28 14:51 UTC, OliwiaMilewska approved these changes

2023-05-28 14:52 UTC, merged