Made Models
AdrianStankiewicz/FreshmanGuide pull request #8
Opened 2023-03-31 18:05 UTC by JakubMajewicz

I made 10 Models for data base project

2023-03-31 19:20 UTC, OliwiaMilewska requested changes

2023-03-31 19:20 UTC, OliwiaMilewska commented on BackProject/Models/Category.cs
> +    public ICollection<Post> Post { get; set; }
Change ICollecton to List.

2023-03-31 19:20 UTC, OliwiaMilewska commented on BackProject/Models/Post.cs
> +        public ICollection<Replie> Replie { get; set; }
Change ICollecton to List.
Replie -> Reply

2023-03-31 19:20 UTC, OliwiaMilewska commented on BackProject/Models/Practice.cs
> +    public class Practice
Change to "Internship".

2023-03-31 19:20 UTC, OliwiaMilewska commented on BackProject/Models/Professor.cs
> +        public String Best_contact { get; set; }
HowToContact

2023-03-31 19:20 UTC, OliwiaMilewska commented on BackProject/Models/Professor.cs
> +        public String TypeOfPass { get; set; }
TypeOfExamination

2023-03-31 19:20 UTC, OliwiaMilewska commented on BackProject/Models/Professor.cs
> +        public ICollection<Consultation> Consultation { get; set; }
ICollection -> List

2023-03-31 19:20 UTC, OliwiaMilewska commented on BackProject/Models/Replie.cs
> +	{
Reply

2023-04-01 14:12 UTC, JakubMajewicz reviewed
I did changes in Models files

2023-04-01 14:33 UTC, OliwiaMilewska requested changes

2023-04-01 14:33 UTC, OliwiaMilewska commented on BackProject/Models/Professor.cs
> +        public List<Consultation> Consultation { get; set; }
To be honest we can make the name here in plural form:
public List<Consultation> Consultations { get; set; }

2023-04-01 14:33 UTC, OliwiaMilewska commented on BackProject/Models/Post.cs
> +        public List<Reply> Reply { get; set; }
To be honest we can make the name here in plural form:
public List<Reply> Replies { get; set; }

2023-04-01 15:08 UTC, JakubMajewicz reviewed
I made names in Models in plural form

2023-04-01 15:10 UTC, OliwiaMilewska approved these changes

2023-04-01 18:41 UTC, AdrianStankiewicz approved these changes

2023-04-01 18:41 UTC, merged